// ── Profile picture definitions ───────────────────────────────────────────────
// Maps ppti tag → { label, color, initials }
const PROFILE_PIC_DEFS = {
  profile_pic_police:    { label: 'POLICE',  color: '#1e40af', accent: '#3b82f6', initials: 'PD' },
  profile_pic_letty01:   { label: 'LETTY',   color: '#7c2d12', accent: '#ef4444', initials: 'L'  },
  profile_pic_roman01:   { label: 'ROMAN',   color: '#14532d', accent: '#22c55e', initials: 'R'  },
  profile_pic_dom01:     { label: 'DOM',     color: '#1c1917', accent: '#a8a29e', initials: 'D'  },
  profile_pic_brian01:   { label: 'BRIAN',   color: '#1e3a5f', accent: '#60a5fa', initials: 'B'  },
  profile_pic_tej01:     { label: 'TEJ',     color: '#3b1f0a', accent: '#f59e0b', initials: 'T'  },
  profile_pic_hobbs01:   { label: 'HOBBS',   color: '#1a2a1a', accent: '#4ade80', initials: 'H'  }
};

function buildProfilePicSvg(tag) {
  const def = PROFILE_PIC_DEFS[tag] || {
    label:    tag.replace(/^profile_pic_/, '').toUpperCase(),
    color:    '#1f2937',
    accent:   '#6b7280',
    initials: tag.replace(/^profile_pic_/, '').slice(0, 2).toUpperCase()
  };

  const { label, color, accent, initials } = def;
  const size = 256;
  const cx   = size / 2;
  const cy   = size / 2;
  const r    = size / 2;

  return [
    `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">`,
    `<defs>`,
    `<radialGradient id="bg" cx="50%" cy="40%" r="60%">`,
    `<stop offset="0%" stop-color="${accent}" stop-opacity="0.4"/>`,
    `<stop offset="100%" stop-color="${color}"/>`,
    `</radialGradient>`,
    `</defs>`,
    // Background circle
    `<circle cx="${cx}" cy="${cy}" r="${r}" fill="url(#bg)"/>`,
    // Outer ring
    `<circle cx="${cx}" cy="${cy}" r="${r - 4}" fill="none" stroke="${accent}" stroke-width="6" stroke-opacity="0.8"/>`,
    // Head silhouette circle
    `<circle cx="${cx}" cy="${cy - 28}" r="48" fill="${accent}" fill-opacity="0.9"/>`,
    // Body silhouette
    `<ellipse cx="${cx}" cy="${cy + 90}" rx="60" ry="48" fill="${accent}" fill-opacity="0.9"/>`,
    // Initials text
    `<text x="${cx}" y="${cy - 18}" text-anchor="middle" dominant-baseline="middle" fill="white" font-size="52" font-family="Arial Black, Arial, sans-serif" font-weight="900">${initials}</text>`,
    // Name label strip
    `<rect x="0" y="${size - 52}" width="${size}" height="52" fill="${color}" fill-opacity="0.9"/>`,
    `<text x="${cx}" y="${size - 20}" text-anchor="middle" dominant-baseline="middle" fill="white" font-size="22" font-family="Arial, sans-serif" font-weight="bold" letter-spacing="2">${label}</text>`,
    `</svg>`
  ].join('');
}

function buildPlaceholderSvg(name) {
  const safeName = String(name || 'asset').replace(/[^a-zA-Z0-9_-]/g, ' ');

  // Profile picture assets get a proper avatar SVG
  if (name && /^profile_pic_/i.test(name)) {
    return buildProfilePicSvg(name);
  }

  return [
    '<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="576">',
    '<rect width="1024" height="576" fill="#111827"/>',
    '<rect x="24" y="24" width="976" height="528" rx="20" fill="#1f2937" stroke="#22c55e" stroke-width="4"/>',
    '<text x="60" y="140" fill="#f9fafb" font-size="54" font-family="Arial, sans-serif">2K Drive Mock Media</text>',
    `<text x="60" y="240" fill="#93c5fd" font-size="36" font-family="Arial, sans-serif">${safeName}</text>`,
    '<text x="60" y="320" fill="#d1d5db" font-size="24" font-family="Arial, sans-serif">Generated by the rebuilt local server scaffold.</text>',
    '</svg>'
  ].join('');
}

module.exports = {
  buildPlaceholderSvg,
  buildProfilePicSvg
};
